version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.31
    - 14.14.32
    - 15.0.0
  - dependency-name: next-pwa
    versions:
    - 5.0.5
    - 5.0.6
    - 5.1.4
    - 5.2.1
    - 5.2.14
    - 5.2.15
    - 5.2.3
    - 5.2.5
    - 5.2.9
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
    - 8.3.0
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.20
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.5
    - 6.2.7
    - 6.2.8
    - 6.2.9
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.21
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
    - 6.2.9
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
    - 7.13.15
    - 7.13.16
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.1
    - 13.0.13
    - 13.0.16
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.16.1
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.22.0
  - dependency-name: styled-icons
    versions:
    - 10.28.0
    - 10.30.0
    - 10.31.0
    - 10.33.0
  - dependency-name: next
    versions:
    - 10.1.2
    - 10.1.3
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: eslint
    versions:
    - 7.23.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: react-slick
    versions:
    - 0.28.1
  - dependency-name: husky
    versions:
    - 5.1.3
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.13.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.5
  - dependency-name: storybook-addon-next-router
    versions:
    - 2.0.4
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: highlight.js
    versions:
    - 10.4.1
